Repository IceFreez3r/Evolution, pull requests merged in 2020-01, with the labels that each got.

#24 Update to print-Functions
  environment.cpp
  main.cpp
  util.cpp
  util.hpp
Labels: documentation, small change

#30 Deleted one direction() call
  dot.cpp
  environment.cpp
Labels: small change

#31 Foodsearch interval
  environment.cpp
Labels: bug

#32 less zeros
  environment.cpp
Labels: documentation, small change
